title: Flywheel Adapt
email: dev@flywheel.co
description: > # this means to ignore newlines until "baseurl:"
    This is a SASS based foundation of commonly used mixins, classes and a default
    reset. It can be pulled into your project via Composer, Bower or download and import.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: flywheelco
# github_username:  flywheel-co
#

sass:
  load_paths:
    - _sass
    - assets/vendor/flywheel-adapt/

# Build settings
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

markdown: kramdown

kramdown:
  parse_block_html: true

collections:
  - sections
  - mixins

highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
# theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
